services:
  influxdb:
    image: influxdb:2.7-alpine
    env_file:
      - ./env/influx.env
    volumes:
      - influxdb_data:/var/lib/influxdb2:rw
    ports:
      - 8086:8086
    expose:
      - 8086
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:9.0.4
    env_file:
      - ./env/grafana.env
    expose:
      - 3000
    networks:
      - monitoring
    volumes:
      - grafana_data:/var/lib/grafana
      - ./conf/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - influxdb
  nginx:
    image: nginx:1.24.0
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - monitoring
    depends_on:
      - grafana

networks:
  monitoring:

volumes:
  influxdb_data:
  grafana_data: